
#CONSULTANDO A VERSÃO DO DOCKER INSTALADA NO SISTEMA
docker --version

#BAIXANDO A IMAGEM "HELLO-WORLD" DO DOCKER HUB
docker pull hello-world-test

#TESTANDO A INSTALAÇÃO DO DOCKER NO SISTEMA
#CASO A IMAGEM NÃO ESTEJA PRESENTE NO SISTEMA, O DOCKER IRÁ BAIXÁ-LA AUTOMATICAMENTE
docker run hello-world-test

#RODANDO UM CONTAINER DA IMAGEM "NGINX" E MAPEANDO A PORTA 80 DO CONTAINER PARA A PORTA 9001 DA MÁQUINA LOCAL
#O PARÂMETRO -d RODA O CONTAINER EM BACKGROUND
#O PARÂMETRO --restart=always GARANTE QUE O CONTAINER SERÁ REINICIADO AUTOMATICAMENTE EM CASO DE FALHA OU REINÍCIO DO SISTEMA
#SUBSTITUA <image_name> PELO NOME DA IMAGEM QUE VOCÊ DESEJA RODAR
docker run -p 9001:80 -d --restart=always <image_name>

#RODANDO UM CONTAINER COM LIMITES DE RECURSOS DE MEMÓRIA E CPU
#LIMITANDO A MEMÓRIA RAM A 512MB, COM SWAP DE 1GB
#LIMITANDO O USO DE CPU A 1.5 CPUs (150% DE UMA CPU)
#LIMITANDO O USO DE CPU A 750 MICROSEGUNDOS A CADA 1000 MICROSEGUNDOS (75% DE UMA CPU)
#SUBSTITUA <container_id> PELO ID DO CONTAINER QUE VOCÊ DESEJA RODAR COM LIMITES DE RECURSOS
docker run -m 512m --memory-swap 1g --cpus="1.5" --cpu-quota 750 <container_id>

#CRIANDO UMA IMAGEM DO DOCKER A PARTIR DO ARQUIVO DOCKERFILE
#PADRÃO DE NOMENCLATURA: nome-da-imagem:versão-da-imagem
#OBS: SUBSTITUA O CAMINHO ABAIXO PELO CAMINHO ONDE ESTÁ O SEU ARQUIVO DOCKERFILE
docker build -t hello-docker-test:0.0.1-SNAPSHOT ./path/to/Dockerfile

#LISTANDO AS IMAGENS DO DOCKER NO SISTEMA; USE UM DOS COMANDOS ABAIXO
docker image ls
docker images

#CRIANDO E RODANDO UM CONTAINER A PARTIR DA IMAGEM CRIADA ANTERIORMENTE
#MAPEANDO A PORTA 80 DO CONTAINER PARA A PORTA 80 DA MÁQUINA LOCAL
#RODANDO O CONTAINER EM BACKGROUND (-d)
docker run -p 80:80 -d hello-docker-test:0.0.1-SNAPSHOT

#LISTANDO OS CONTAINERS DO DOCKER NO SISTEMA; USE UM DOS COMANDOS ABAIXO
docker container ls
docker ps

#UPLOAD DA IMAGEM PARA O DOCKER HUB
#PASSO 1: FAÇA LOGIN NO DOCKER HUB
docker login
#PASSO 2: MARQUE (TAG) A IMAGEM LOCAL COM O NOME DO SEU USUÁRIO NO DOCKER HUB
#SUBSTITUA your_dockerhub_username PELO SEU NOME DE USUÁRIO NO DOCKER HUB
#O PARÂMETRO tag NESTE COMANDO SERVE PARA ATRIBUIR À IMAGEM LOCAL O NOME QUE SERÁ USADO NO DOCKER HUB
docker tag hello-docker-test:0.0.1-SNAPSHOT your_dockerhub_username/hello-docker:0.0.1-SNAPSHOT
#PASSO 3: FAÇA O PUSH DA IMAGEM PARA O DOCKER HUB
docker push your_dockerhub_username/hello-docker:0.0.1-SNAPSHOT

#LOGOUT DO DOCKER HUB
docker logout

#PARANDO E REMOVENDO O CONTAINER RODANDO A IMAGEM
#SUBSTITUA <container_id> PELO ID DO CONTAINER QUE VOCÊ DESEJA PARAR E REMOVER
docker container stop <container_id>

#PARA TODOS OS CONTAINERS EM EXECUÇÃO
docker stop --all

#FORÇANDO A PARADA DE UM CONTAINER EM EXECUÇÃO
docker container kill <container_id>

#COMANDO PARA REMOVER O CONTAINER PARADO
docker container rm <container_id>

#REMOVENDO TODOS OS CONTAINERS PARADOS
docker container prune

#PAUSANDO E DESPAUSANDO UM CONTAINER EM EXECUÇÃO
docker container pause <container_id>
docker container unpause <container_id>

#REMOVENDO A IMAGEM DO DOCKER DO SISTEMA LOCAL
docker image rmi hello-docker:0.0.1-SNAPSHOT

#VISUALIZANDO OS LOGS DO CONTAINER
docker logs <container_id>
#VISUALIZAÇÃO DOS LOGS EM TEMPO REAL (FOLLOW)
#ESTE COMANDO COLOCA O TERMINAL EM MODO DE ACOMPANHAMENTO DOS LOGS, 
#NÃO PERMITINDO OUTRAS INTERAÇÕES ATÉ QUE SEJA INTERROMPIDO COM CTRL+C
docker logs -f <container_id>

#BUSCANDO IMAGENS NO DOCKER HUB
#EXEMPLO: BUSCANDO A IMAGEM DO MYSQL COM FILTRO DE IMAGENS OFICIAIS
docker search mysql --filter is-official=true

#VISUALIZANDO O HISTÓRICO DE UMA IMAGEM DO DOCKER
#ESTE COMANDO EXIBE CADA CAMADA (LAYER) QUE COMPÕE A IMAGEM,
#JUNTAMENTE COM INFORMAÇÕES COMO O COMANDO USADO PARA CRIAR A CAMADA,
#O TAMANHO DA CAMADA E O TIMESTAMP DE SUA CRIAÇÃO
#CORRESPONDE AOS COMANDOS DEFINIDOS NO DOCKERFILE
docker image history <image_id>

#INSPECIONANDO UMA IMAGEM OU CONTAINER DO DOCKER
#ESTE COMANDO FORNECE INFORMAÇÕES DETALHADAS EM FORMATO JSON SOBRE A IMAGEM OU CONTAINER ESPECIFICADO,
#INCLUINDO CONFIGURAÇÕES, VARIÁVEIS DE AMBIENTE, PORTAS EXPOSAS, VOLUMES, E OUTROS METADADOS
docker inspect <image_id ou container_id>

#ACESSANDO O TERMINAL INTERATIVO DE UM CONTAINER EM EXECUÇÃO
#O PARÂMETRO -i MANTÉM A SESSÃO INTERATIVA ABERTA
#O PARÂMETRO -t ALLOCA UM TERMINAL TTY
docker exec -it <container_id> /bin/bash

#ACESSANDO O TERMINAL INTERATIVO DE UM CONTAINER PARADO
docker run -it hello-docker:0.0.1-SNAPSHOT /bin/bash

#REMOVENDO UMA IMAGEM DO DOCKER PELO ID OU NOME
docker image remove <image_id/nome_da_imagem>
docker image rm <image_id/nome_da_imagem>
docker rmi <image_id/nome_da_imagem>

#FORÇANDO A REMOÇÃO DE UMA IMAGEM DO DOCKER (CASO ESTEJA SENDO USADA POR UM CONTAINER)
docker image rm <image_id/nome_da_imagem> -f

#REMOVENDO TODAS AS IMAGENS NÃO UTILIZADAS (DANIFICADAS)
docker image prune -a

#VISUALIZANDO OS PROCESSOS RODANDO DENTRO DE UM CONTAINER
docker top <container_id>

#MONITORANDO O USO DE RECURSOS DE UM CONTAINER (CPU, MEMÓRIA, REDE, DISCO)
docker stats <container_id>

#============================================================================
#DOCKER COMPOSE COMMANDS

#INICIA OS CONTÂINERES CONFORME ESPECIFICAÇÕES DO ARQUIVO
docker-compose up
docker-compose up -d
docker-compose up --build

#ENCERRA TODOS OS CONTÂINERES E RECURSOS EXECUTADOS ATRAVÉS DO ARQUIVO
docker-compose down

#EXIBE AS INFORMAÇÕES E STATUS APENAS DOS RECURSOS ESPECIFICADOS NO ARQUIVO
docker-compose ps
